### ISSUE TITLE
Error: spawn mongodump ENOENT

### ISSUE THREAD

**Issue by khalidMhd** [trulymittal/mongodb_backup_nodejs#1]
error:
 Error: spawn mongodump ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn mongodump',
  path: 'mongodump',
  spawnargs: [
    '--db=polio',
    '--archive=C:\\Users\\samsung\\Desktop\\mongodb_backup_nodejs-master\\public\\polio.gzip',
    '--gzip'
  ]
}

**Comment by khalidMhd** [comment]
solved:
pass this: {shell: true}
 const child = spawn('mongodump', [
    `--db=${DB_NAME}`,
    `--archive=${ARCHIVE_PATH}`,
    '--gzip',
  ], {shell: true});

**Comment by khalidMhd** [comment]
this issue

stderr:
 'mongodump' is not recognized as an internal or external command,
operable program or batch file.
